<a href="https://colab.research.google.com/github/exponential-tortoise/PyTorch_Basics/blob/master/Broadcasting_and_Element_wise_Operationswith.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import torch
import numpy as np

In [4]:
t1 = torch.tensor([
    [1,2],
    [3,4]
], dtype=torch.float32)

t2 = torch.tensor([
    [9,8],
    [7,6]
], dtype=torch.float32)


t1+t2

tensor([[10., 10.],
        [10., 10.]])

In [6]:
print(t1+2)

print(t1.add(2))

tensor([[3., 4.],
        [5., 6.]])
tensor([[3., 4.],
        [5., 6.]])


Broadcasting describes how tensors with different shapes are treated during element-wise operations. 
" Broadcasting is the concept whose implementation allows us to add scalars to higher dimensional tensors. "

In [9]:
np.broadcast_to(2,t1.shape)

array([[2, 2],
       [2, 2]])

Comparison

In [10]:
torch.tensor([1, 2, 3]) < torch.tensor([3, 1, 2])

tensor([ True, False, False])

In [11]:
t = torch.tensor([
    [0,5,0],
    [6,0,7],
    [0,8,0]
], dtype=torch.float32)

In [12]:
t.eq(0)

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])

In [13]:
t.ge(0)  # greater or equal 

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [16]:
t.le(7)  # less or equal to 7 

tensor([[ True,  True,  True],
        [ True,  True,  True],
        [ True, False,  True]])

In [18]:
t.lt(5)  #less than 5 

tensor([[ True, False,  True],
        [False,  True, False],
        [ True, False,  True]])