In [2]:
import torch
import numpy as np

In [3]:
t=torch.Tensor()
type(t)

torch.Tensor

In [4]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.float32
cpu
torch.strided


Creating tensors from Data . 


In [5]:
lst=[1,2,3]
print(type(lst))

<class 'list'>


In [6]:
torch.Tensor(lst)

tensor([1., 2., 3.])

In [7]:
torch.tensor(lst)

tensor([1, 2, 3])

In [8]:
torch.as_tensor(lst)

tensor([1, 2, 3])

In [9]:
lst1=np.array(lst)
torch.from_numpy(lst1)


tensor([1, 2, 3])

In [10]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [11]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
torch.ones(1,3)

tensor([[1., 1., 1.]])

In [13]:
torch.rand(6,2)  # create a 6X2 matrix with random values 

tensor([[0.4433, 0.9274],
        [0.3365, 0.6025],
        [0.6339, 0.2289],
        [0.1310, 0.3017],
        [0.3331, 0.5106],
        [0.2806, 0.6376]])

In [16]:
t=torch.tensor([
                [1,1,1],
                [2,2,2],
                [3,3,3]
],dtype=torch.float32)

print(t)

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])


In [17]:
t.size()


torch.Size([3, 3])

In [18]:
t.shape

torch.Size([3, 3])

In [19]:
t.numel()

9

In [27]:
print(t.reshape(3,3,1))

tensor([[[1.],
         [1.],
         [1.]],

        [[2.],
         [2.],
         [2.]],

        [[3.],
         [3.],
         [3.]]])


In [31]:
t.reshape(9,1).squeeze()


tensor([1., 1., 1., 2., 2., 2., 3., 3., 3.])